### ISSUE TITLE
Add if/else if the `title` field is missing?

### ISSUE THREAD

**Issue by cmilando** [valeriangalliat/notion-property-to-content#2]
Hi! this is a really helpful script, thanks for publishing.
I had to make a quick edit to mine because some `title` fields were missing, which caused the code to break (line 54 in the current commit):
`const title = page.properties.Name.title[0].plain_text`
Might make sense to a js catch for this case (which is common), but I'm not a js expert yet, so I'll leave it to you. Thanks

**Comment by valeriangalliat** [comment]
Thanks for reporting! Better late than never 🙈 just fixed this
